// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Role_Society_Mapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Role_Society_Mapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201911161024579_User_Role_Society_Mapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
