// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_Flat_Balcony : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Flat_Balcony));
        
        string IMigrationMetadata.Id
        {
            get { return "201911200955111_added_Flat_Balcony"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
