// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Flats_Tenants_Map : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Flats_Tenants_Map));
        
        string IMigrationMetadata.Id
        {
            get { return "201911120849302_Flats_Tenants_Map"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
