// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_phoneno_in_societystaff__shifttypephoneno_securitystaff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_phoneno_in_societystaff__shifttypephoneno_securitystaff));
        
        string IMigrationMetadata.Id
        {
            get { return "201911221203010_added_phoneno_in_societystaff_&_shifttype&phoneno_securitystaff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
