// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Map_MaintenanceCost_N_Flat_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Map_MaintenanceCost_N_Flat_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201911080502410_Map_MaintenanceCost_N_Flat_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
