// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Main_Cost_SocietyId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Main_Cost_SocietyId));
        
        string IMigrationMetadata.Id
        {
            get { return "201911131702288_Main_Cost_SocietyId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
