// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SocietyId_Added_ForDuplicay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocietyId_Added_ForDuplicay));
        
        string IMigrationMetadata.Id
        {
            get { return "201911210609481_SocietyId_Added_ForDuplicay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
