// <auto-generated />
namespace ApnaCHS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Flat_FlatType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Flat_FlatType));
        
        string IMigrationMetadata.Id
        {
            get { return "201911110600136_Flat_FlatType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
